### ISSUE TITLE
autoconf test for HAVE_FFMPEG may need to link with -lavutil to work properly

### ISSUE THREAD

**Issue by crazzell** [ejurgensen/forked-daapd#115]
I have ffmpeg-2.5.4 installed in /usr/local and have been trying to build the latest forked-daapd from this git against it. The standard build instructions failed during compilation of artwork.c with `incompatible type for argument 1 of ‘avcodec_find_best_pix_fmt2’`

My workaround to fix this in my system was the following one-line patch to configure.ac
```
--- configure.ac.orig	2015-02-28 03:03:42.548109230 -0800
+++ configure.ac	2015-02-28 03:26:55.294065821 -0800
@@ -151,7 +151,7 @@
 
 save_LIBS="$LIBS"
 AC_CHECK_LIB([avcodec], [avcodec_find_best_pix_fmt_of_list],
-	AC_DEFINE(HAVE_FFMPEG, 1, [Define to 1 if you have ffmpeg (and not libav).]))
+	AC_DEFINE(HAVE_FFMPEG, 1, [Define to 1 if you have ffmpeg (and not libav).]),,[-lavutil])
 LIBS="$save_LIBS"
 
 # Check for libavformat >= 53; url -> avio switch
```

Without this patch, the ./configure script is failing due to multiple undefined references including the following:
```
/usr/local/lib/libavcodec.a(imgconvert.o): In function `avcodec_get_chroma_sub_sample':
/home/debian/ffmpeg-2.5.4/libavcodec/imgconvert.c:45: undefined reference to `av_pix_fmt_desc_get'
/home/debian/ffmpeg-2.5.4/libavcodec/imgconvert.c:46: undefined reference to `av_log'
/usr/local/lib/libavcodec.a(imgconvert.o): In function `avcodec_find_best_pix_fmt_of_2':
/home/debian/ffmpeg-2.5.4/libavcodec/imgconvert.c:61: undefined reference to `av_find_best_pix_fmt_of_2'
```

**Comment by ejurgensen** [comment]
I can't reproduce this error, for me it builds fine with ffmpeg 2.5.4. Since you have ffmpeg in /usr/local - do you have libav in /usr? I don't know, maybe could make a difference.
